feat: add commands
EzarDev/eZaR pull request #17
Opened 2022-07-17 17:08 UTC by toolifelesstocode

This pull request adds all the commands that will basically finish up this re-write. A lot of commands have been tested, but any reviews and help by anyone is appreciated.

2022-07-17 17:38 UTC, ooliver1 requested changes

2022-07-17 17:38 UTC, ooliver1 commented on ezar/cogs/misc.py
> +            user: Member = await itr.guild.getch_member(user.id)
This basically does the exact same as `get_member`, checking if it exists. "Getch" is useless in the fact that the member is already in the cache for this to run. `in` checks every member whereas `get_member` uses a dictionary which has a constant lookup time - hella fast.

2022-07-17 17:38 UTC, ooliver1 commented on ezar/cogs/misc.py
> +            await itr.send(embed=avatar_embed)
```suggestion
        if type == "global":
            avatar_embed.set_image(url=user.avatar.url or user.default_avatar.url)
            avatar_embed.set_author(
                name=user.name, icon_url=user.avatar.url or user.default_avatar.url
            )
        elif type == "local":
            avatar_embed.set_author(name=user.name, icon_url=user.display_avatar.url)
            avatar_embed.set_image(url=user.display_avatar.url)

        await itr.send(embed=avatar_embed)
```
ignore github's awful diff, this just removes duplication of `itr.send`

2022-07-17 17:38 UTC, ooliver1 commented on ezar/cogs/misc.py
> +        user: User = None,
```suggestion
        user: Optional[User] = None,
```
This would require an import, but as you use vscode, I would recommend setting
```toml
[tool.pyright]
typeCheckingMode = "basic"
```
in `pyproject.toml`, and/or `"python.analysis.typeCheckingMode": "basic",` in vscode settings for actual type checking if you wish (Maybe a github check? but that might be a bit far for now).

2022-07-17 18:43 UTC, toolifelesstocode commented on ezar/cogs/misc.py
> +        user: User = None,
A GitHub check may be alright, but yes, I suppose it's alright for now, but thank you.

2022-07-20 18:05 UTC, ooliver1 requested changes

2022-07-20 18:05 UTC, ooliver1 commented on ezar/cogs/misc.py
> +            name="Created", value=f"<t:{round(guild.created_at.timestamp())}>"
utils.format_dt

2022-07-20 18:05 UTC, ooliver1 commented on ezar/cogs/misc.py
> +        info_embed.add_field(name="Rule Channel", value=guild.rules_channel.mention)
what if `rules_channel` is `None`

2022-07-20 18:28 UTC, toolifelesstocode commented on ezar/cogs/misc.py
> +        info_embed.add_field(name="Rule Channel", value=guild.rules_channel.mention)
it will just return None then.

2022-07-20 18:34 UTC, toolifelesstocode commented on ezar/cogs/misc.py
> +            name="Created", value=f"<t:{round(guild.created_at.timestamp())}>"
This isn't _that_ necessary, but sure 👍🏼

2022-07-20 21:15 UTC, ooliver1 commented on ezar/cogs/misc.py
> +        info_embed.add_field(name="Rule Channel", value=guild.rules_channel.mention)
but `NoneType.mention` does not exist

2022-07-20 21:16 UTC, ooliver1 commented on ezar/cogs/misc.py
> +            name="Created", value=f"<t:{round(guild.created_at.timestamp())}>"
it would look much cleaner
```diff
-name="Created", value=f"<t:{round(guild.created_at.timestamp())}>"
+name="Created", value=format_dt(guild.created_at, style="F")
```

2022-07-21 05:32 UTC, toolifelesstocode commented on ezar/cogs/misc.py
> +        info_embed.add_field(name="Rule Channel", value=guild.rules_channel.mention)
I forgor :skull:

2022-07-21 21:59 UTC, ooliver1 commented on pyproject.toml
>  python = "^3.8"
Don't you think that these should go in a separate PR, instead of a long-lasting draft?

2022-07-22 05:29 UTC, toolifelesstocode commented on pyproject.toml
>  python = "^3.8"
Good idea, I'll move them to main.

2022-07-27 20:18 UTC, toolifelesstocode commented
The following commits will be moved to https://github.com/eZaR-Bot/eZaR/tree/main:
- [`2e033b1` (#17)](https://github.com/eZaR-Bot/eZaR/pull/17/commits/2e033b14de0936713bf61f1efa5162aa13137554)
- [`ff91073` (#17)](https://github.com/eZaR-Bot/eZaR/pull/17/commits/ff910738e5f18eeddb71e7b383e397cd550ea510)

2022-08-15 11:17 UTC, toolifelesstocode commented
Make this PR stalen't.

2022-08-15 11:43 UTC, ooliver1 commented
> Make this PR stalen't. :trollface:

Ok give me command to do :trollface:

2022-08-15 12:53 UTC, toolifelesstocode commented
> > Make this PR stalen't. :trollface:
> 
> Ok give me command to do :trollface:

Given on the Discord guild, ty.

2022-08-17 14:28 UTC, Skelmis requested changes

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/economy.py
> +        return
This is not needed

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/economy.py
> +        return
This is not needed

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/economy.py
> +        user: The user to view."""
Newline after `view.`

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/misc.py
> +        type: The type of avatar to get."""
newline after `get.`

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/misc.py
> +        user: The user to get information about."""
newline after `about.`

2022-08-17 14:28 UTC, Skelmis commented on ezar/cogs/misc.py
> +        role: The role to get information about."""
newline after `about.`

2022-08-17 14:49 UTC, toolifelesstocode commented on ezar/cogs/economy.py
> +        return
The `self.stop`'s were added because the `on_timeout` listener would still fire even though the `return` statement is there.

2022-08-17 15:02 UTC, Skelmis commented on ezar/cogs/economy.py
> +        return
My comment isn't on the stop, it's on the return

2022-08-27 19:01 UTC, toolifelesstocode commented
Well that was funny :joy:

2022-11-03 07:16 UTC, toolifelesstocode commented
Closing this due to the privating of eZaR. Although the entire repo _might_ be refactored, not sure.

2022-11-03 07:16 UTC, closed without merging