feat: add workflows and checks on PR
EzarDev/eZaR pull request #19
Opened 2022-08-12 16:03 UTC by yusufadell

Creating workflows and checks for the repository. The following workflows have bee added:

[flake8](https://flake8.pycqa.org/en/latest/)
[black](https://black.readthedocs.io/en/stable/index.html)
[isort](https://pycqa.github.io/isort/)

2022-08-12 16:13 UTC, toolifelesstocode requested changes
Thanks so much for this! I just have some very minor change requests then it looks good to me

2022-08-12 16:13 UTC, toolifelesstocode commented on .github/workflows/ci.yaml
> +                  python-version: 3.9
```suggestion
                  python-version: 3.8
```

2022-08-12 16:13 UTC, toolifelesstocode commented on .github/workflows/ci.yaml
> +            - name: Set up Python 3.9
```suggestion
            - name: Set up Python 3.8
```

2022-08-12 16:20 UTC, yusufadell commented
> Thanks so much for this! I just have some very minor change requests then it looks good to me. The minimum Python version you need is Python 3.8 for this bot so please can you just change those.

Done!

2022-08-12 18:31 UTC, ooliver1 requested changes

2022-08-12 18:31 UTC, ooliver1 commented on .github/workflows/ci.yaml
> +        branches: ["master", "main"]
Why is this locked to branches?

2022-08-12 18:31 UTC, ooliver1 commented on tox.ini
> +max-line-length = 120
This file can probably be removed as it is duplicate config of `setup.cfg`

2022-08-12 18:31 UTC, ooliver1 commented on setup.cfg
> +[isort]
Could isort use `format = "black`? Most of this config can then be removed like wrap and `use_parentheses`

2022-08-14 10:36 UTC, yusufadell commented on .github/workflows/ci.yaml
> +        branches: ["master", "main"]
Here CI/workflow makes sure that we follow a consistent coding style. and doing so for not yet merges branches is quite redundant work.

2022-08-14 10:54 UTC, toolifelesstocode approved these changes
Besides Oliver's requests, LGTM

2022-08-14 11:26 UTC, ooliver1 commented on .github/workflows/ci.yaml
> +        branches: ["master", "main"]
The branch is always main or master, it can’t be both at the same time

2022-08-15 10:29 UTC, ooliver1 approved these changes

2022-08-15 10:29 UTC, merged