feat: add guild event logging
EzarDev/eZaR pull request #27
Opened 2022-09-02 18:09 UTC by ooliver1

closes #24

## Reasons For Seemingly Unrelated Changes

`ezar/__main__.py` - embedded modules such as `ezar.cogs.logs.messages` can be resolved - better directory structure
`ezar/helpers/components.py` - so slash command interaction's responses can be edited, instead of component interactions' messages being edited

## Examples

![message edit](https://user-images.githubusercontent.com/34910574/188212270-048d04fc-2985-492a-a02f-002f296f1856.png)
![message delete](https://user-images.githubusercontent.com/34910574/188212346-d644ba5d-9728-40d9-8446-de6588d1a024.png)
![bulk message delete](https://user-images.githubusercontent.com/34910574/188212733-69db6f3f-4108-40e1-bdf7-dc4daa58143b.png)

This code so far has been tested, the aim is for all events in #24 to be handled, as seen in `ezar.cogs.logs.__init__.LOG_TYPES`.

2022-09-11 20:06 UTC, toolifelesstocode requested changes
Looks awesome! Just have a few requests :)

2022-09-11 20:06 UTC, toolifelesstocode commented on ezar/cogs/logs/messages.py
> +            embed = Embeb(title="Multiple Messages Deleted", description=description)
Could we have it send a .txt file to make it show the deleted messages? Yes it does state that multiple messages were deleted, but it'd be great if it showed what messages were deleted, if possible.

File Structure:
```txt
Messages Deleted: {count}

{Message} - {Message author}
``` 
or something like that

2022-09-13 13:04 UTC, toolifelesstocode approved these changes
lgtm

2022-09-13 13:06 UTC, ooliver1 commented
LETS FUCKING GOOOO

2022-09-13 13:07 UTC, merged